### ISSUE TITLE
Add GitHub action built-in support

### ISSUE THREAD

**Issue by BenJeau** [callstack/react-native-builder-bob#123]
## Describe the feature
To have built-in GitHub action support. The script could ask the user if they want to use CircleCI or GitHub Actions.

## Motivation
Since GitHub Actions are supported without any modification (compared to CircleCI), it may be a great way to easily integrate CI/CD.

**Comment by satya164** [comment]
I love GitHub actions for taks like triaging issues, automating some tasks in the issue. But regarding CI/CD, one big problem with GitHub actions is that it's not possible to persist some stuff between multiple workflows. This means that you need to install dependencies separately for every workflow which is pretty slow. It's possible to upload node_modules as an artifact and then download it on other workflows, but in my experience, it's been as slow so no real improvements.

Do you know any way to fix this? If this can be solved, then I would love to have GitHub actions as the CI.

**Comment by BenJeau** [comment]
You are right, their current solution is either storing `node_modules` as an artifact or using the cache. The first option really doesn't seem ideal as you said, but the second one doesn't seem that bad. I guess what we could do is have a job that install the dependencies, save it in the cache, and make the other jobs depend on that job where they would just pull the cache and do their own task. I'm not sure if it works well, but it seems like a not too bad option.

On a side note, I just tried using CircleCI and it works really well, it improved a lot since the last time I used it. I'll be using that for now,

**Comment by mrousavy** [comment]
Hey! I'm a big fan of creating ready to use GH actions because until now I've written them by hand everytime. I have a few working examples here if you want to take a look: [react-native-vision-camera/.github/workflows](https://github.com/cuvent/react-native-vision-camera/tree/frame-processors/.github/workflows)

**Comment by BartoszKlonowski** [comment]
@BenJeau @satya164  Perhaps instead of deciding between GitHub and CircleCI both should be supported, and additional question should be implemented that would allow a developer/user to choose between them or have them both.

If somebody is aware of the GitHub disadvantage you discussed, or for some reason prefers to use GH Actions over CircleCI, then we should support this direction as well.

**Comment by satya164** [comment]
Added in https://github.com/callstack/react-native-builder-bob/commit/3bad82db17675d366db18d8eb5d137f5d00802aa
