### ISSUE TITLE
How to import BOB package not published on npm?

### ISSUE THREAD

**Issue by Overtorment** [callstack/react-native-builder-bob#132]
I have a situation where I cant publish my BOB package to npm because of huge bundled binaries (AAR and dot framework), npm just doesn't accept this upload. So I have to consume my package via github URL. This generally works with other packages, but with BOB I've run into some issues and I don't know if Im missing something.

My configuration:

```
  "main": "lib/commonjs/index",
  "module": "lib/module/index",
  "types": "lib/typescript/src/index.d.ts",
  "react-native": "src/index",
  "source": "src/index",
  "files": [
    "src",
    "lib",
    "android",
    "ios",
    "cpp",
    "rn-lnd.podspec",
    "!lib/typescript/example",
    "!android/build",
    "!ios/build",
    "!**/__tests__",
    "!**/__fixtures__",
    "!**/__mocks__"
  ],
```
...

```
  "react-native-builder-bob": {
    "source": "src",
    "output": "lib",
    "targets": [
      "commonjs",
      "module",
      [
        "typescript",
        {
          "project": "tsconfig.build.json"
        }
      ]
    ]
  }
```

I had to commit my locally built `lib/`.
Whats strange is that there is no root index.js like in other packages, and when I just try to import it my  IDE says module not installed:
![image](https://user-images.githubusercontent.com/1913337/106784832-abbc8480-6644-11eb-83fe-383e348b0242.png)

empirically I figured out that this works:

```
import RnLnd from 'rn-lnd/lib/module';
```

but that doesn't feel right. what am I missing?

PS. package on github: https://github.com/BlueWallet/rn-lnd

**Comment by shamilovtim** [comment]
I use BOB with packages not on npm (local file based .tgz packages) and have no issues. They also include frameworks and AAR files. I'm not sure where your problem is coming in, but I use BOB's settings as is, and they work fine with no npm distribution. I would assume you're doing something wrong in the `/src/index.js` file and investigate how you're exporting from that file, and whether you're overriden any standard bob scaffolding.

**Comment by aprotsyk** [comment]
+1
