### ISSUE TITLE
Running yarn doesn't work

### ISSUE THREAD

**Issue by johannbuscail** [callstack/react-native-builder-bob#190]
## Description

When I initialize a library with  `npx create-react-native-library app-structure` everything works fine, the folder is created.
But in the doc, the next step is to run `yarn`, and when I run it, nothing happens. **It stops directly**

I tried updating `yarn` to the latest version and even uninstall and reinstalling it, but it doesn't change anything.

Strangely, when I run `npm install` instead of yarn, some things are installed but still, if I run `npm run example web`, nothing happens.

## Reproducible Demo

Simply run `npx create-react-native-library app-structure`, then `yarn`

**Comment by a-elcesar** [comment]
> ## Description
> When I initialize a library with `npx create-react-native-library app-structure` everything works fine, the folder is created.
> But in the doc, the next step is to run `yarn`, and when I run it, nothing happens. **It stops directly**
> 
> I tried updating `yarn` to the latest version and even uninstall and reinstalling it, but it doesn't change anything.
> 
> Strangely, when I run `npm install` instead of yarn, some things are installed but still, if I run `npm run example web`, nothing happens.
> 
> ## Reproducible Demo
> Simply run `npx create-react-native-library app-structure`, then `yarn`

Hi ngab.
I assume you were running this on windows, because it runs fine on MacOS.
The problem is that somehow nodejs behaves differently on windows, it can't spawn the child_process automatically. Do the following:

- Go to /scripts directory in the root project
- Edit the bootstrap.js, pass the key { shell: true }

So the  options would be like this:
`const options = {
  cwd: process.cwd(),
  env: process.env,
  stdio: 'inherit',
  encoding: 'utf-8',
  **shell: true,**
};`

**Comment by sunel** [comment]
Can we you add this in the readme, 2 hours i was clueless.

**Comment by lfabl** [comment]
I think, a pr should be opened for this.

**Comment by MateWW** [comment]
@lfabl Is this issue still happening for you?
It seems to be already resolved:
https://github.com/callstack/react-native-builder-bob/blob/3bad82db17675d366db18d8eb5d137f5d00802aa/packages/create-react-native-library/templates/common/scripts/bootstrap.js#L15

**Comment by lfabl** [comment]
Yes, i solved with shell = true;
