### ISSUE TITLE
How to edit iOS/Android module after setup?

### ISSUE THREAD

**Issue by curiousdustin** [callstack/react-native-builder-bob#237]
## Ask your Question

Are there any docs or tutorials on adding to the templated native modules after setup?

The [React Native Docs](https://reactnative.dev/docs/native-modules-setup) briefly tell how to use `create-react-native-library` to setup a module project. This worked great, and looks like a good place to start.

However I am confused as to what is the best way to continue from here and make edits.

For instance, if I open `my-library/ios/my-library.xcodeproj` There are immediately errors such as: `'React/RCTBridgeModule.h' file not found` or `@objc attribute used without importing module 'Foundation'`...

I know these aren't actually problems because the generated example app works just fine, and I can make edits to the included `multiply()` code and they work as well.

But, how can I make edits without blindly writing code in a broken environment and then rebuilding the example?

I have the same basic question for Android.

**Comment by satya164** [comment]
You open your example project with XCode and Android studio and edit the module from there. It will be somewhere in the dependency tree.

**Comment by curiousdustin** [comment]
Thanks for the quick reply.

So instead of opening `my-library/ios/my-library.xcodeproj`, I should be opening `my-library/example/ios/my-libraryExample.xcworkspace`?

I do see `my-library` within the `Pods` section of this workspace. However, if I try to add files to this it tells me it is going to add files toe `Pods` not to my project.

Is this what I should be doing?

**Comment by curiousdustin** [comment]
Thanks for the tips. This worked for me, although a little confusing. I found I had to run `pod install` each time I made certain edits to the main Xcode project such as adding new files.

**Comment by trevorwhealy** [comment]
Similar issue here. Have no idea how to work around the errors since pressing build fails on an otherwise clean setup. In theory, I know the code is working since the example capably runs, but not sure if there are steps missing. I currently have no meaningful way to actually edit or extend the native code due to the build errors.

<img width="995" alt="Screenshot 2022-12-08 at 1 55 39 PM" src="https://user-images.githubusercontent.com/14946478/206575827-99854e8b-bb28-4f92-9db0-e48002ad885f.png">
