### ISSUE TITLE
--react-native-version is invalid

### ISSUE THREAD

**Issue by AsteriskZuo** [callstack/react-native-builder-bob#321]
### Description

create new one project with last version
```sh
npx create-react-native-library --languages "java-objc" --type "library" --react-native-version "0.68.2" test_rn_library
```
but, it is ok
```sh
react-native init test_rn_library2 --directory test_rn_library2 --version "0.68.2" --skip-install
```

create-react-native-library and react-native-builder-bob
```sh
npx react-native-builder-bob --version
# 0.20.0
npx create-react-native-library --version
# 0.26.0
```

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

npx create-react-native-library --languages "java-objc" --type "library" --react-native-version "0.68.2" test_rn_library

### Environment

npx react-native-builder-bob --version
# 0.20.0
npx create-react-native-library --version
# 0.26.0

**Comment by AsteriskZuo** [comment]
How to debug in development mode, I can help fix.

**Comment by MateWW** [comment]
Our CLI does not support a selection of RN versions right now.
Especially right now it will be hard due to rapidly changing modules API.
It would be simply hard to maintain that code.

As a workaround:
- generate the library without specifying the version
- remove the `example` directory
- create an example with `npx react-native init`
- apply manually changes from [here](https://github.com/callstack/react-native-builder-bob/tree/main/packages/create-react-native-library/templates/example-legacy)

However, I cannot give you a warranty it will work correctly.

**Comment by MateWW** [comment]
We are struggling currently with a lack of consistency validation across properties in the CLI.

Try using our wizard that will save you from doing mistakes like this
```
npx create-react-native-library@latest --react-native-version "0.68.2" test_rn_library
```

**Comment by MateWW** [comment]
This should save us from issues like this in future
#322

**Comment by AsteriskZuo** [comment]
I understand. Thank you very much for your detailed reply.

**Comment by AsteriskZuo** [comment]
It is ok.
```sh
npx create-react-native-library --languages "java-objc" --type "module-legacy" --react-native-version "0.68.2" test_rn_library3
```
