### ISSUE TITLE
How to Install other Npm Packages that require Native Modules setup?

### ISSUE THREAD

**Issue by aibrahim3546** [callstack/react-native-builder-bob#95]
# Question
How to install other npm packages inside the created react native modules.
For example, I have created a custom Map modules of my own. e.g CustomMaps.
And I would like to add `react-native-maps` in this modules. So that anyone use my custom modules will have the `react-native-maps library`  installed when they install my CustomModules in their project.

**Comment by Vluf** [comment]
Also having problems getting this kind of setup to work. The auto-linking for the other native modules seem to fail.

**Comment by Vluf** [comment]
Seems like this is already a known issue: https://github.com/react-native-community/bob/issues/89

**Comment by AmalMenachery** [comment]
We are currently using the mapbox-gl, for a component. We are customizing the component as required and export our component in index. For the example App for make it work, we have added the mapbox-gl package in example project too. Is it required to add the mapbox-gl package in the Application where we install our library ,since the mapbox-gl is mentioned in the library dependencies ? This should be automatically installed while we installed the library right ?

**Comment by Vluf** [comment]
@AmalMenachery Yes it should, but the native part won't be linked if you only include it in the library dependencies. That's the essence of this issue, I believe.

**Comment by Vluf** [comment]
So the `metro.config.js` file that comes with the example app is actually configured for this. You should add your native dependencies to your peer dependencies instead of the usual dependencies.
This fixed it for me and linked up everything as expected.

Of course, make sure that the peer dependencies are installed in the library's `node_modules`

**Comment by AmalMenachery** [comment]
@Vluf Thanks Man !

**Comment by Vluf** [comment]
@AmalMenachery I was too quick I believe. This does not solve the issue.

However, I believe the correct way is to add native dependencies as `peerDependencies` in the library and therefore also add them to example's `dependencies`. This way has been working for me since the beginning but feels a bit ugly.
